version: '3'

services:
  postgres:
    build:
      context: ./docker/postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "${DB_PORT}:${DB_PORT}"
  
  nodejs:
    build:
      context: ./docker/nodejs
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    
