version: '3'

services:
  postgres:
    image: postgres:16.2-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  nodejs:
    image: b0nam/marvelnft:node
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    command: npm start
