version: '3'

services:
  postgres:
    image: b0nam/marvelnft:postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  nodejs:
    image: bonam/marvelnft:node
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"
