name: Build and Deploy
run-name: Build and deploy docker images on dockerhub

on: [push, workflow_dispatch]
jobs:
    build_postgres_job:
      runs-on: ubuntu-latest

      steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Autenticate with Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}

          - name: Build marvelnft postgres
            run: docker build -t marvelnft:postgres docker/postgres/.

          - name: Push marvelnft postgres
            run: |
              docker tag marvelnft:postgres "${{ secrets.DOCKERHUB_USERNAME }}/marvelnft:postgres"
              docker push "${{ secrets.DOCKERHUB_USERNAME }}/marvelnft:postgres"

    build_node_job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Autenticate with Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build marvelnft node
              run: docker build -t marvelnft:node docker/node/.

            - name: Push marvelnft node
              run: |
                docker tag marvelnft:node "${{ secrets.DOCKERHUB_USERNAME }}/marvelnft:node"
                docker push "${{ secrets.DOCKERHUB_USERNAME }}/marvelnft:node"
          