name: Build and Deploy
run-name: Build and deploy docker images on dockerhub

on: [push, workflow_dispatch]
jobs:
    build_node_job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Autenticate with Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build marvelnft node
              run: docker build -t marvelnft:node .

            - name: Push marvelnft node
              run: |
                docker tag marvelnft:node "${{ secrets.DOCKERHUB_USERNAME }}/marvelnft:node"
                docker push "${{ secrets.DOCKERHUB_USERNAME }}/marvelnft:node"

    aplication_unit_tests:
        needs: build_node_job
        runs-on: ubuntu-latest
          
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          
          - name: Pull docker image
            run: docker pull "${{ secrets.DOCKERHUB_USERNAME }}/marvelnft:node"
          
          - name: Run tests on docker image
            run: |
              docker run "${{ secrets.DOCKERHUB_USERNAME }}/marvelnft:node" npm test
              exit_code=$?
              if [ $exit_code -eq 0 ]; then
                echo "[+] All tests passed successfuly!"
              else
                echo "[-] Test failures!"
                exit $exit_code
              fi

    aplication_load_tests:
        needs: aplication_unit_tests
        runs-on: ubuntu-latest
          
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          
          - name: Start docker compose
            run: docker-compose up
          
          - name: Start load tests
            run: curl localhost:3000/ping